// app/(dashboard)/layout.tsx

import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/navigation/sidebar";
import Header from "@/components/navigation/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex">
      <nav className="h-screen">
        <Sidebar />
      </nav>
      <main className="flex-1">
        <Header userName={"Nigga"} className="flex w-full" />
        {children}
      </main>
    </div>
  );
}
